//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebServiceInteractor.SKGeliosWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IRustourService", Namespace="http://tempuri.org/")]
    public partial class RustourService : Microsoft.Web.Services2.WebServicesClientProtocol {
        
        private System.Threading.SendOrPostCallback LoadPolicyOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletePolicyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RustourService() {
            this.Url = global::WebServiceInteractor.Properties.Settings.Default.WebServiceInteractor_SKGeliosWebService_RustourService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoadPolicyCompletedEventHandler LoadPolicyCompleted;
        
        /// <remarks/>
        public event DeletePolicyCompletedEventHandler DeletePolicyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IRustourService/LoadPolicy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WS_NS_Policy_Result LoadPolicy([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string serviceKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] WS_NS_Policy policy) {
            object[] results = this.Invoke("LoadPolicy", new object[] {
                        serviceKey,
                        policy});
            return ((WS_NS_Policy_Result)(results[0]));
        }
        
        /// <remarks/>
        public void LoadPolicyAsync(string serviceKey, WS_NS_Policy policy) {
            this.LoadPolicyAsync(serviceKey, policy, null);
        }
        
        /// <remarks/>
        public void LoadPolicyAsync(string serviceKey, WS_NS_Policy policy, object userState) {
            if ((this.LoadPolicyOperationCompleted == null)) {
                this.LoadPolicyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadPolicyOperationCompleted);
            }
            this.InvokeAsync("LoadPolicy", new object[] {
                        serviceKey,
                        policy}, this.LoadPolicyOperationCompleted, userState);
        }
        
        private void OnLoadPolicyOperationCompleted(object arg) {
            if ((this.LoadPolicyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadPolicyCompleted(this, new LoadPolicyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IRustourService/DeletePolicy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WS_NS_Policy_Result DeletePolicy([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string serviceKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] WS_NS_PolicyTo_Del policy) {
            object[] results = this.Invoke("DeletePolicy", new object[] {
                        serviceKey,
                        policy});
            return ((WS_NS_Policy_Result)(results[0]));
        }
        
        /// <remarks/>
        public void DeletePolicyAsync(string serviceKey, WS_NS_PolicyTo_Del policy) {
            this.DeletePolicyAsync(serviceKey, policy, null);
        }
        
        /// <remarks/>
        public void DeletePolicyAsync(string serviceKey, WS_NS_PolicyTo_Del policy, object userState) {
            if ((this.DeletePolicyOperationCompleted == null)) {
                this.DeletePolicyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletePolicyOperationCompleted);
            }
            this.InvokeAsync("DeletePolicy", new object[] {
                        serviceKey,
                        policy}, this.DeletePolicyOperationCompleted, userState);
        }
        
        private void OnDeletePolicyOperationCompleted(object arg) {
            if ((this.DeletePolicyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletePolicyCompleted(this, new DeletePolicyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/iCra.Core.Domain")]
    public partial class WS_NS_Policy {
        
        private string claimField;
        
        private string countryField;
        
        private System.DateTime creationDateField;
        
        private bool creationDateFieldSpecified;
        
        private System.DateTime endDateField;
        
        private bool endDateFieldSpecified;
        
        private string idField;
        
        private WS_NS_Client[] insuredsField;
        
        private WS_NS_Client insurerField;
        
        private bool insurerIsInsuredField;
        
        private bool insurerIsInsuredFieldSpecified;
        
        private System.DateTime payDateField;
        
        private bool payDateFieldSpecified;
        
        private string policyNumberField;
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        private decimal tourPriceUEField;
        
        private bool tourPriceUEFieldSpecified;
        
        private string townFromField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Claim {
            get {
                return this.claimField;
            }
            set {
                this.claimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreationDateSpecified {
            get {
                return this.creationDateFieldSpecified;
            }
            set {
                this.creationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public WS_NS_Client[] Insureds {
            get {
                return this.insuredsField;
            }
            set {
                this.insuredsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WS_NS_Client Insurer {
            get {
                return this.insurerField;
            }
            set {
                this.insurerField = value;
            }
        }
        
        /// <remarks/>
        public bool InsurerIsInsured {
            get {
                return this.insurerIsInsuredField;
            }
            set {
                this.insurerIsInsuredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InsurerIsInsuredSpecified {
            get {
                return this.insurerIsInsuredFieldSpecified;
            }
            set {
                this.insurerIsInsuredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PayDate {
            get {
                return this.payDateField;
            }
            set {
                this.payDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PayDateSpecified {
            get {
                return this.payDateFieldSpecified;
            }
            set {
                this.payDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PolicyNumber {
            get {
                return this.policyNumberField;
            }
            set {
                this.policyNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal TourPriceUE {
            get {
                return this.tourPriceUEField;
            }
            set {
                this.tourPriceUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TourPriceUESpecified {
            get {
                return this.tourPriceUEFieldSpecified;
            }
            set {
                this.tourPriceUEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TownFrom {
            get {
                return this.townFromField;
            }
            set {
                this.townFromField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/iCra.Core.Domain")]
    public partial class WS_NS_Client {
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private string doc_NumberField;
        
        private string firstNameField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string lastNameField;
        
        /// <remarks/>
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Doc_Number {
            get {
                return this.doc_NumberField;
            }
            set {
                this.doc_NumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/iCra.Core.Domain")]
    public partial class WS_NS_PolicyTo_Del {
        
        private System.DateTime deletedDateField;
        
        private bool deletedDateFieldSpecified;
        
        private string idField;
        
        /// <remarks/>
        public System.DateTime DeletedDate {
            get {
                return this.deletedDateField;
            }
            set {
                this.deletedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeletedDateSpecified {
            get {
                return this.deletedDateFieldSpecified;
            }
            set {
                this.deletedDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/iCra.Core.Domain")]
    public partial class WS_NS_Client_Result {
        
        private int clientIdField;
        
        private bool clientIdFieldSpecified;
        
        private decimal premiumField;
        
        private bool premiumFieldSpecified;
        
        /// <remarks/>
        public int ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClientIdSpecified {
            get {
                return this.clientIdFieldSpecified;
            }
            set {
                this.clientIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Premium {
            get {
                return this.premiumField;
            }
            set {
                this.premiumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PremiumSpecified {
            get {
                return this.premiumFieldSpecified;
            }
            set {
                this.premiumFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/iCra.Core.Domain")]
    public partial class WS_NS_Policy_Result {
        
        private string errorMessageField;
        
        private decimal exchangeRateField;
        
        private bool exchangeRateFieldSpecified;
        
        private string insuranceVariantNVField;
        
        private WS_NS_Client_Result[] insuredPremiumsField;
        
        private byte[] policyBytesField;
        
        private string policyNumberField;
        
        private decimal premiumMR_UEField;
        
        private bool premiumMR_UEFieldSpecified;
        
        private decimal premiumNV_UEField;
        
        private bool premiumNV_UEFieldSpecified;
        
        private bool resultField;
        
        private bool resultFieldSpecified;
        
        private decimal sumOneInsuredMRField;
        
        private bool sumOneInsuredMRFieldSpecified;
        
        private decimal sumOneInsuredMR_UEField;
        
        private bool sumOneInsuredMR_UEFieldSpecified;
        
        private decimal sumOneInsuredNVField;
        
        private bool sumOneInsuredNVFieldSpecified;
        
        private decimal sumOneInsuredNV_UEField;
        
        private bool sumOneInsuredNV_UEFieldSpecified;
        
        private decimal totalPremiumField;
        
        private bool totalPremiumFieldSpecified;
        
        private decimal totalPremiumUEField;
        
        private bool totalPremiumUEFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public decimal ExchangeRate {
            get {
                return this.exchangeRateField;
            }
            set {
                this.exchangeRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExchangeRateSpecified {
            get {
                return this.exchangeRateFieldSpecified;
            }
            set {
                this.exchangeRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InsuranceVariantNV {
            get {
                return this.insuranceVariantNVField;
            }
            set {
                this.insuranceVariantNVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public WS_NS_Client_Result[] InsuredPremiums {
            get {
                return this.insuredPremiumsField;
            }
            set {
                this.insuredPremiumsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] PolicyBytes {
            get {
                return this.policyBytesField;
            }
            set {
                this.policyBytesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PolicyNumber {
            get {
                return this.policyNumberField;
            }
            set {
                this.policyNumberField = value;
            }
        }
        
        /// <remarks/>
        public decimal PremiumMR_UE {
            get {
                return this.premiumMR_UEField;
            }
            set {
                this.premiumMR_UEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PremiumMR_UESpecified {
            get {
                return this.premiumMR_UEFieldSpecified;
            }
            set {
                this.premiumMR_UEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PremiumNV_UE {
            get {
                return this.premiumNV_UEField;
            }
            set {
                this.premiumNV_UEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PremiumNV_UESpecified {
            get {
                return this.premiumNV_UEFieldSpecified;
            }
            set {
                this.premiumNV_UEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResultSpecified {
            get {
                return this.resultFieldSpecified;
            }
            set {
                this.resultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal SumOneInsuredMR {
            get {
                return this.sumOneInsuredMRField;
            }
            set {
                this.sumOneInsuredMRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SumOneInsuredMRSpecified {
            get {
                return this.sumOneInsuredMRFieldSpecified;
            }
            set {
                this.sumOneInsuredMRFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal SumOneInsuredMR_UE {
            get {
                return this.sumOneInsuredMR_UEField;
            }
            set {
                this.sumOneInsuredMR_UEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SumOneInsuredMR_UESpecified {
            get {
                return this.sumOneInsuredMR_UEFieldSpecified;
            }
            set {
                this.sumOneInsuredMR_UEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal SumOneInsuredNV {
            get {
                return this.sumOneInsuredNVField;
            }
            set {
                this.sumOneInsuredNVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SumOneInsuredNVSpecified {
            get {
                return this.sumOneInsuredNVFieldSpecified;
            }
            set {
                this.sumOneInsuredNVFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal SumOneInsuredNV_UE {
            get {
                return this.sumOneInsuredNV_UEField;
            }
            set {
                this.sumOneInsuredNV_UEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SumOneInsuredNV_UESpecified {
            get {
                return this.sumOneInsuredNV_UEFieldSpecified;
            }
            set {
                this.sumOneInsuredNV_UEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalPremium {
            get {
                return this.totalPremiumField;
            }
            set {
                this.totalPremiumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalPremiumSpecified {
            get {
                return this.totalPremiumFieldSpecified;
            }
            set {
                this.totalPremiumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalPremiumUE {
            get {
                return this.totalPremiumUEField;
            }
            set {
                this.totalPremiumUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalPremiumUESpecified {
            get {
                return this.totalPremiumUEFieldSpecified;
            }
            set {
                this.totalPremiumUEFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void LoadPolicyCompletedEventHandler(object sender, LoadPolicyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadPolicyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadPolicyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WS_NS_Policy_Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WS_NS_Policy_Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DeletePolicyCompletedEventHandler(object sender, DeletePolicyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeletePolicyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeletePolicyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WS_NS_Policy_Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WS_NS_Policy_Result)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591